/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ABC_Institute;

import com.mysql.cj.protocol.Resultset;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author kozz
 */
public class sub_details extends javax.swing.JFrame {

    Connection conn  ;
    PreparedStatement pst  ;
    ResultSet RS ;
    
    public sub_details() {
        initComponents();
        showTableData();
    }
    
    public void showTableData()
        {
            try{
                conn = DriverManager.getConnection("jdbc:mysql://localhost/prabuddha","root","");
                String sql = "SELECT * FROM subdetails WHERE 1";
                pst = conn.prepareStatement(sql);
                RS = pst.executeQuery();
                jtable2.setModel(DbUtils.resultSetToTableModel(RS));
            }
            catch(Exception Ex){
            JOptionPane.showMessageDialog(null,Ex);
            
            }
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jyear = new javax.swing.JComboBox();
        jname = new javax.swing.JTextField();
        jcode = new javax.swing.JTextField();
        jlec = new javax.swing.JTextField();
        jtute = new javax.swing.JTextField();
        jlab = new javax.swing.JTextField();
        jeva = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jsem = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add and Manage Subjects");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(80, 195, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Offerd Semester");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 96, 197, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Subject Code");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 232, 197, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Number of Tutorial hours");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 96, 197, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Subject Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 164, 197, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Offerd Year");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 38, 197, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Number of Lab hours");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 164, 197, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Number of Evaluation hours");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 232, 197, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Number of Lecture hours");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 38, 197, 40));

        jyear.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jPanel2.add(jyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 38, 198, 40));

        jname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnameActionPerformed(evt);
            }
        });
        jPanel2.add(jname, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 165, 198, 40));

        jcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcodeActionPerformed(evt);
            }
        });
        jPanel2.add(jcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 233, 198, 40));

        jlec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlecActionPerformed(evt);
            }
        });
        jlec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jlecKeyTyped(evt);
            }
        });
        jPanel2.add(jlec, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 39, 198, 40));

        jtute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtuteActionPerformed(evt);
            }
        });
        jtute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtuteKeyTyped(evt);
            }
        });
        jPanel2.add(jtute, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 97, 198, 40));

        jlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlabActionPerformed(evt);
            }
        });
        jlab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jlabKeyTyped(evt);
            }
        });
        jPanel2.add(jlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 165, 198, 40));

        jeva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jevaActionPerformed(evt);
            }
        });
        jeva.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jevaKeyTyped(evt);
            }
        });
        jPanel2.add(jeva, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 233, 198, 40));

        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Offerd Year", "Offerd Semester", "Subject Name", "Subject Code", "Lec Hrs", "Tute Hrs", "Lab Hrs", "Eval Hrs"
            }
        ));
        jtable2.setShowHorizontalLines(false);
        jtable2.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jtable2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 291, 1212, -1));

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 751, 103, 38));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1137, 751, 95, 38));

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 751, 95, 38));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 729, 83, -1));

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel2.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 751, 94, 38));

        jsem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));
        jPanel2.add(jsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 98, 198, 39));

        jButton3.setBackground(new java.awt.Color(80, 195, 195));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 763, 83, -1));

        jButton6.setFont(new java.awt.Font("Tw Cen MT", 1, 12)); // NOI18N
        jButton6.setText("Manage Lectures");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 748, 368, 44));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 1270, 810));
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnameActionPerformed

    private void jcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcodeActionPerformed

    private void jlecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlecActionPerformed

    private void jtuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtuteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtuteActionPerformed

    private void jlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabActionPerformed

    private void jevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jevaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jyear.setToolTipText("");
        jsem.setToolTipText("");
        jname.setText("");
        jcode.setText("");
        jlec.setText("");
        jtute.setText("");
        jlab.setText("");
        jeva.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         try{
           
            
            String subCode = jcode.getText();
            String sql = "delete from subdetails where Code= '"+subCode+"'";
            pst= conn.prepareStatement(sql);
            
             
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
            showTableData();
        
        }
        catch(Exception ex){
        
            JOptionPane.showMessageDialog(null, "Nothing to delete");
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            
            String sql = "update subdetails set Year= ?, Semester= ?, Name= ?, Code= ?, Lec_hrs= ?, Tute_hrs= ?, Lab_hrs= ?, Eva_hrs= ? WHERE Code= ?";
            pst = conn.prepareStatement(sql);
            
            pst.setString(9,jcode.getText());
            
            String year = jyear.getSelectedItem().toString();
            pst.setString(1,year);
            
            String sem = jsem.getSelectedItem().toString();
            pst.setString(2,sem);
            
            
            String name = jname.getText();
            pst.setString(3,name);
            
            
            String code = jcode.getText();
            pst.setString(4,code);
            
            String lec = jlec.getText();
            pst.setString(5,lec);
            
            String tute = jtute.getText();
            pst.setString(6,tute);
            
            String lab = jlab.getText();
            pst.setString(7,lab);
            
            pst.setString(8,jeva.getText());
            
             
            
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated Successfully");
            showTableData();
            
        }
        catch (Exception ex){
            
        JOptionPane.showMessageDialog(null, "Nothing to update");
        
        
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
                        
        try {
            String sql = "INSERT INTO subdetails"
                    +"(Year, Semester, Name, Code, Lec_hrs, Tute_hrs, Lab_hrs, Eva_hrs)"
                    + "VALUES (?,?,?,?,?,?,?,?)";
            
            conn = DriverManager.getConnection("jdbc:mysql://localhost/prabuddha","root","");
            pst = conn.prepareStatement(sql);
            
            pst.setString(1,jyear.getSelectedItem().toString());
            pst.setString(2,jsem.getSelectedItem().toString());
            
            
            String name = jname.getText();
            pst.setString(3,name);
            
            
            String code = jcode.getText();
            pst.setString(4,code);
            
            String lec = jlec.getText();
            pst.setString(5,lec);
            
            String tute = jtute.getText();
            pst.setString(6,tute);
            
            String lab = jlab.getText();
            pst.setString(7,lab);
            
            pst.setString(8,jeva.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");
            showTableData();
            
        }
        catch (Exception ex){
            
        JOptionPane.showMessageDialog(null, "Fill all the Details!!!");
        
        
        }
        
        
    }//GEN-LAST:event_saveActionPerformed

    private void jlecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlecKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_jlecKeyTyped

    private void jtuteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtuteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jtuteKeyTyped

    private void jlabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlabKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jlabKeyTyped

    private void jevaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jevaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jevaKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        showTableData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        new mysqlconn().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sub_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sub_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sub_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sub_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sub_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jcode;
    private javax.swing.JTextField jeva;
    private javax.swing.JTextField jlab;
    private javax.swing.JTextField jlec;
    private javax.swing.JTextField jname;
    private javax.swing.JComboBox jsem;
    private javax.swing.JTable jtable2;
    private javax.swing.JTextField jtute;
    private javax.swing.JComboBox jyear;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
